# Aprendizaje de Máquina - Laboratorio 3

## Integrantes

| Nombre             | Código    | Correo electrónico           |
|--------------------|-----------|------------------------------|
| Adrian Velasquez   | 202222737 | a.velasquezs@uniandes.edu.co |
| Andres Botero Ruiz | 202223503 | a.boteror@uniandes.edu.co    |

In [9]:
# Definición de constantes

DATA_PATH = './data/'
DATA_FILE = DATA_PATH + 'data.csv'
TEST_FILE = DATA_PATH + 'test.csv'

In [10]:
# Importar librerias

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
# Cargar los datos
df = pd.read_csv(DATA_FILE, encoding='iso-8859-1', delimiter=';')
df.head()

,Edad,Gnereo,Peso,Altura,BMI,Objetivo,Condicion_salud,Nivel_Actividad,Nivel_experiencia,Dieta_preferida,...,Fumador,Cigarrillos_dia,Alcohol,Alcohol_semana,Score_micronutrientes,Ingesta_proteinas,Pasos_dia,Ingesta_agua,Plan_entrenamiento,Plan_nutrición
0,60,Masculino,73.7,1.61,28.43,Resistencia,Hipertension,Bajo,Avanzado,Vegano,...,0,0.0,0,0.0,0.92,182.1,16485,2.49,Medio,Sin plan
1,17,Femenino,121.0,1.97,31.18,Resistencia,Enfermedad corazon,Moderado,Principiante,Vegetariano,...,0,0.0,0,0.0,0.76,167.7,14256,2.04,Ninguno,Sin plan
2,43,Masculino,110.0,1.52,47.61,General,Ninguno,Bajo,Principiante,No-Vegetariano,...,0,0.0,0,0.0,0.34,104.9,3050,2.53,Bajo,Basico
3,49,Otro,73.6,1.96,19.16,General,Ninguno,Moderado,Principiante,No-Vegetariano,...,0,0.0,0,0.0,0.71,59.5,2264,3.36,Ninguno,Sin plan
4,53,Femenino,80.8,1.76,26.08,Resistencia,Hipertension,Alto,Principiante,Pescetariano,...,1,8.7,0,0.0,0.98,51.1,12774,1.90,Medio,Sin plan

In [12]:
# Limpiar columnas
df['Genero'] = df['Gnereo'] # Corregir el typo
df = df.drop(columns=['Gnereo'])

# Poner columnas en minuscula
df.columns = df.columns.str.lower()

df.sample(5)

,edad,peso,altura,bmi,objetivo,condicion_salud,nivel_actividad,nivel_experiencia,dieta_preferida,horas_sueño,...,cigarrillos_dia,alcohol,alcohol_semana,score_micronutrientes,ingesta_proteinas,pasos_dia,ingesta_agua,plan_entrenamiento,plan_nutrición,genero
2235,34,67.4,1.84,19.91,Resistencia,Ninguno,Moderado,Principiante,Vegano,5.5,...,0.0,0,0.0,0.47,194.7,2723,3.69,Ninguno,Sin plan,Femenino
4269,59,127.8,1.85,37.34,Resistencia,Ninguno,Alto,Avanzado,Pescetariano,6.6,...,0.0,0,0.0,0.03,209.2,11111,2.38,Alto,Basico,Femenino
8016,29,116.3,1.79,36.30,Ganancia muscular,Enfermedad corazon,Bajo,Intermedio,Vegano,8.9,...,0.0,0,0.0,0.61,150.1,10884,4.47,Medio,Balanceado,Masculino
2542,23,48.0,2.01,11.88,General,Ninguno,Moderado,Intermedio,Vegano,5.1,...,0.0,1,7.8,0.27,112.1,15754,2.88,Ninguno,Basico,Masculino
1803,37,83.1,1.87,23.76,Perdida grasa,Ninguno,Moderado,Avanzado,No-Vegetariano,5.4,...,0.0,1,21.4,0.21,84.3,6276,3.49,Bajo,Balanceado,Masculino